services:
  - type: web
    runtime: docker
    name : swapbox-backend
    plan : free
    region : singapore
    repo : https://github.com/nnoeytcx/swapBox.git
    branch: deploy-render
    rootDir : backend
    envVars :
      - key : PORT
        value : 8000
      - key : DJANGO_SECRET_KEY
        value : "django-insecure-m7c-yxg$z4pbvgd=f@1o_)vv&1daw99ff(a%_x^eg&w!4ynv#d"
      - key : DEBUG
        value : "False"

  - type : web
    runtime: docker
    name : swapbox-frontend
    plan : free
    region : singapore
    repo : https://github.com/nnoeytcx/swapBox.git
    branch: deploy-render
    rootDir : frontend
    envVars :
      - key : PORT
        value : 80