services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: ENV_VAR_NAME
        value: some_value
    buildCommand: ""
    startCommand: "python manage.py runserver 0.0.0.0:8000"

  - type: web
    name: frontend
    env: docker
    dockerfilePath: swaparea/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend.onrender.com
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
