# Generated by Django 5.2 on 2025-05-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapback', '0002_alter_chat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
