# Generated by Django 5.2 on 2025-05-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapback', '0005_remove_item_created_at_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
