# Generated by Django 5.2 on 2025-05-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapback', '0008_item_swap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='swap',
            field=models.CharField(max_length=255),
        ),
    ]
