# Generated by Django 5.2 on 2025-05-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapback', '0006_remove_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='swapback.item'),
        ),
    ]
