# Generated by Django 5.2 on 2025-05-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapback', '0007_alter_like_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='swap',
            field=models.TextField(blank=True),
        ),
    ]
